version: '3'
services:
  mongodb:
    container_name: "falcon_mongodb"
    image: mongo:latest    
    ports:
      - "27017:27017"
    network_mode: "host"
    environment:
      MONGO_DATA_DIR: \data\db
     
       